import '../Models/car_model.dart';

List mileageList = [
  "10",
  "20",
  "30",
  "50",
  "100",
];

List fuelTypeList = [
  "Diesel",
  "CNG",
  "Electric",
  "Electric / Diesel",
  "Electric / Gasoline",
];

List transmissionList = ["Automatic", "Manual"];

List yearList = [
  "2024",
  "2023",
  "2022",
  "2021",
  "2020",
  "2019",
  "2018",
  "2017",
  "2016",
  "2015",
  "2014",
  "2013",
  "2012",
  "2011",
  "2010",
  "2009",
  "2008",
  "2007",
  "2006",
  "2005",
  "2004",
  "2003",
  "2002",
  "2001",
  "2000",
  "- 1999"
];

List bodyTypeList = [
  "Coupe",
  "Hatchback",
  "SUV",
  "Sedan",
  "Wagon",
  "Sport",
  "Hybrid",
];

List<String> carCompaniesList = [
  "Abarth",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Bugatti",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Dacia",
  "Daewoo",
  "Daihatsu",
  "Dodge",
  "Donkervoort",
  "DS",
  "Ferrari",
  "Fiat",
  "Fisker",
  "Ford",
  "Honda",
  "Hummer",
  "Hyundai",
  "Infiniti",
  "Iveco",
  "Jaguar",
  "Jeep",
  "Kia",
  "KTM",
  "Lada",
  "Lamborghini",
  "Lancia",
  "Land Rover",
  "Landwind",
  "Lexus",
  "Lotus",
  "Maserati",
  "Maybach",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MG",
  "Mini",
  "Mitsubishi",
  "Morgan",
  "Nissan",
  "Opel",
  "Peugeot",
  "Porsche",
  "Renault",
  "Rolls-Royce",
  "Rover",
  "Saab",
  "Seat",
  "Skoda",
  "Smart",
  "SsangYong",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo"
];

List<String> countriesList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua & Deps",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Rep",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo {Democratic Rep}",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland {Republic}",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea North",
  "Korea South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "St Kitts & Nevis",
  "St Lucia",
  "Saint Vincent & the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome & Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad & Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

List<CarModel> cars = [
  CarModel(
      0,
      "BMW 225d",
      "endo per passaggio ad altra macchina La macchina è un full optional praticamente , al listino di optional mancano solo il tettuccio e le telecamere 360 e basta. L auto è stata tagliandata fino a 85000 km in bmw di seguito dopo il mio acquisto è stata tagliandata dal mio meccanico di fiducia e l'ultimo tagliando è stato eseguito il 15 maggio. La macchina monta -assetto kw v1 (1700?) -cerchi replica m2cs (1500?) -impianto frenante 6 pompanti davantiE due pompanti dietro con dischi baffatti e forati dietroE forati davanti brembo con pastiglie ebc blu davanti e ferodo racing dietro e tubi in treccia annessi , con verniciatura estorial blu per le pinze (3200?)La macchina di serie è un 2000 ,4 cilindri biturbo da 224cv ed è stata eseguita una mappa soft che la porta sui 270 cv e 530nm di coppia scaricati tutti nella trazione posteriore , per le gomme son state montate delle hankook s1 evo 3 , le anteriori sono al 60% mentre le posteriori all 80%Non sognatori o perditempo , contattare su whatsappIl prezzo è trattabileDaniele",
      "Coupe",
      "New",
      "BMW",
      "Italy",
      "29.000",
      "2022",
      "130.000",
      "Diesel",
      "Automatic", [
    "assets/images/bmw/bmw1.jpg",
    "assets/images/bmw/bmw2.jpg",
    'assets/images/bmw/bmw3.jpg',
    'assets/images/bmw/bmw4.jpg',
    'assets/images/bmw/bmw5.jpg'
  ])
];

List<String> carOptionList = [
  "Electronic Parking Brake",
  "360 View Camera",
  "Automatic Parking Assist",
  "Night Vision Assist",
  "Adaptive Cruise Control",
  "Cruise Control",
  "Digital Cockpit",
  "Heads Up Display(HUD)",
  "Blind Spot Monitor",
  "Hill Assist",
  "Electronic Stability Program (ESP)",
  "Tyre Pressure Monitoring System (TPMS)",
  "ABS+EBD",
  "Automatic Climate Control",
  "Dual Zone Climate Control",
  "Anti Pinch Power Windows",
  "Heated ORVM",
  "Hill Descent Control",
  "Apple car play/ Android auto",
  "Hands-Free Tailgate",
  "Mild Hybrid",
  "Driving Mode",
  "Real Time Vehicle Tracking",
  "Engine Immobilizer",
  "Limited Slip Differential (LSD)",
  "Steering Adjustment Type",
  "Mileage (ARAI)",
  "Tachometer",
  "Xenon Headlamps/HID",
  "Body Kit",
  "Rear Spoiler",
  "Seat Lumbar Support",
  "Adjustable Lumbar Support",
  "Tailgate Ajar Sensor",
  "Voice Command/ Control",
  "Electrically Adjustable Headrests",
  "Active Noise Cancellation",
  "Smart Key Band",
  "Paddle Shifters",
  "Lane Change Indicator",
  "Traction Control",
  "Pre-Safe Sound",
  "Child Seat Anchor Points aka ISOFIX",
  "Follow Me Home Headlamps",
  "Dual-Stage Airbags",
  "Differential Lock",
  "Engine Check Warning",
  "Pretensioners and Force Limiters Seatbelts",
  "SOS/ Emergency Assistance",
  "Cornerning Brake Control",
  "Geo-Fence Alert",
  "Kerb Weight",
  "Gross Weight",
  "Max Power",
  "Max Torque",
  "Minimum Turning Radius",
  "Transmission Type",
  "Drivetrain",
  "Supercharger",
  "Turbocharger",
  "Displacement",
  "Keyless Entry",
  "Smart Access Card Entry",
];
